### ISSUE TITLE
Page Type Migration: Media Library Form Control backed by Text field

### ISSUE THREAD

**Issue by mcbeev** [Kentico/xperience-migration-toolkit#125]
### Brief bug description

For KX13 Page Types that are a data type of Text and use the Media Selector Form Control:

![image](https://user-images.githubusercontent.com/9918767/221376772-b9fd889e-12f3-44d8-9f19-82fad7bfb211.png)

The migration toolkit brings those fields over into Xperience by Kentico as Text fields

![image](https://user-images.githubusercontent.com/9918767/221376818-ea6722e9-302b-4ffb-b434-16eb79aca83f.png)

This makes those types of fields unusable in Xperience by Kentico when you try to use them as Media Library selectors in Xperience because you have to change the type to Media Library but the value of the field is not the expected JSON format.

![image](https://user-images.githubusercontent.com/9918767/221376928-906f197f-7ed3-413d-96ac-4452b882c6d0.png)

### Repro steps

1. Migrate command that uses --media-libraries to migrate via the CLI
2. Change a given page type that has a field that should be a media file selector.
3. Attempt to load that page in the pages app - edit mode.

### Expected behavior

What is the correct behavior?

I should be able to use the field as a Media Library selector without the Pages app causing a 500.

**Comment by mcbeev** [comment]
Thanks for the update @tkrch, I think your specific answer makes sense. However, I think this is a very common use case for Kentico projects. I think there should be something different that happens here though as I have 250 blog posts to migrate and now basically won't have images for each one of them if nothing changes.

**Comment by seangwright** [comment]
All of our sites built since K12 MVC have used the text field of Page Types to store paths created by the Media Selector or URL Selector (with only the media library tab).

This inserts urls with the `/getmedia/...` path as the text value of the field.

We then use a Regex on this value to extract the `Guid` of the Media File and retrieve the file from the database to access the Description, Width, Height properties.

So this feature would be extremely important for us to be able to migrate any site to XbyK.

Make this a configurable setting would be nice.

But, this has me thinking about the extensibility story for the Migration Toolkit - are developers expected to fork, modify the source and then build the toolkit to handle use cases that it doesn't support?

Maybe there's a plugin/extension model that could let the Toolkit hand off migration of specific data to custom code/assembly without rebuilding the tool to get the custom functionality 🤔.
